[tool.poetry]
name = "nhlapi"
version = "0.1.0"
description = ""
authors = ["Simon Bernier St-Pierre <sbernierstpierre@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^3.8"
sphinx = "^1.8"
sphinxcontrib-fulltoc = "^1.2"
